### ISSUE TITLE
Even simpler conventions?

### ISSUE THREAD

**Issue by beddari** [lvillani/vagrant-metadata#1]
Great project, thanks, I'm going to use it as part of my Packer toolchain. I thought I'd mention I changed it a bit for my own use case, like this

https://github.com/beddari/vagrant-metadata/commit/8bb39049dc8188cd4b73ef2eb2a3a1819b16c271

I think this is even simpler :)

**Comment by lvillani** [comment]
I'm not sure it's simpler, maybe just... different? :wink: 

The advantage of my approach is that I can just take the output folder created by boxcutter's Packer templates and slap that on a server. It also makes for (slightly) cleaner URLs.

Your approach has the benefit that all boxes (for a certain version) are inside the same directory.

I think both approaches to be perfectly fine but I believe that it would be even better to add an "import" command to read the provider name from the `metadata.json` file within the box and let `vagrant-metadata` place/rename the file accordingly (unfortunately that's not something I can work on at the moment).

**Comment by beddari** [comment]
Yeah, I agree, just different. Reading from within the box would be the end-all solution, yes ;-)

Closing.
